#!/usr/bin/env python3


import json
import locale
import sys
import reports
import emails

def load_data(filename):
  """Loads the contents of filename as a JSON file."""
  with open(filename) as json_file:
    data = json.load(json_file)
  return data


def format_car(car):
  """Given a car dictionary, returns a nicely formatted name."""
  return "{} {} ({})".format(car["car_make"], car["car_model"], car["car_year"])


def process_data(data):
  """Analyzes the data, looking for maximums.

  Returns a list of lines that summarize the information.
  """
  max_revenue = {"revenue": 0}
  max_sales = {"total_sales": 0} # Guardamos el máximo de ventas que se ha encontrado en el for de abajo
  datos_coche_mas_ventas = {} # Guardamos el item con más ventas
  year_more_sales = {} # Guardamos el año como clave y vamos aumentando recuento en valor para misma clave
  for item in data:
    # Calculate the revenue generated by this model (price * total_sales)
    # We need to convert the price from "$1234.56" to 1234.56
    item_price = locale.atof(item["price"].strip("$"))
    item_revenue = item["total_sales"] * item_price
    if item_revenue > max_revenue["revenue"]:
      item["revenue"] = item_revenue
      max_revenue = item

    # TODO: also handle max sales
    if item["total_sales"] > max_sales["total_sales"]:
      max_sales["total_sales"] = item["total_sales"]
      datos_coche_mas_ventas = item["car"]

    # TODO: also handle most popular car_year
    if item["car"]["car_year"] not in year_more_sales.keys():
      year_more_sales[item["car"]["car_year"]] = item["total_sales"]
    else:
      year_more_sales[item["car"]["car_year"]] = year_more_sales[item["car"]["car_year"]] + item["total_sales"]

    

  summary = [
    "The {} generated the most revenue: ${}".format(format_car(max_revenue["car"]), max_revenue["revenue"]),
  ]
  summary.append("The {} had the most sales: {}".format(format_car(datos_coche_mas_ventas), max_sales["total_sales"]))

  #Para dar el año y las ventas totales:
  tupla_max_key_value = max(zip(year_more_sales.values(), year_more_sales.keys()))
  summary.append("The most popular year was {} with {} sales.".format(tupla_max_key_value[1], tupla_max_key_value[0]))

  return summary    
def cars_dict_to_table(car_data):
  """Turns the data in car_data into a list of lists."""
  table_data = [["ID", "Car", "Price", "Total Sales"]]
  for item in car_data:
    table_data.append([item["id"], format_car(item["car"]), item["price"], item["total_sales"]])
  return table_data


def main(argv):
  """Process the JSON data and generate a full report out of it."""
  data = load_data("car_sales.json")
  summary = process_data(data)
  print(summary)
  # TODO: turn this into a PDF report
  reports.generate("/tmp/cars.pdf") ####TERMINAR
  # TODO: send the PDF report as an email attachment
  

if __name__ == "__main__":
  main(sys.argv)